# Travis CI Configuration File - For Testing

# Tell Travis CI the languages being used
language: php

# PHP version to test against
php:
  - 5.5
  - 5.4
  - hhvm
language: java

#Specify which branch to test
#env:
#	- WP_VERSION=master WP_MULTISITE=0
